
CREATE SCHEMA IF NOT EXISTS `weatherdb` DEFAULT CHARACTER SET utf8 ;

USE `weatherdb` ;

CREATE TABLE IF NOT EXISTS `WEATHER_DAY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `max_degree` INT NULL,
  `min_degree` INT NULL,
  `symbol_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `WEATHER_HOUR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wind_speed` FLOAT NULL,
  `wind_direction` VARCHAR(20) NULL,
  `symbol_url` VARCHAR(45) NULL,
  `humidity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `DAY_HOUR` (
  `DAY_id` INT NOT NULL,
  `HOUR_id` INT NOT NULL,
  `time` INT NULL,
  INDEX `fk_table1_WEATHER_HOUR_idx` (`HOUR_id` ASC),
  INDEX `fk_table1_WEATHER_DAY1_idx` (`DAY_id` ASC),
  CONSTRAINT `fk_table1_WEATHER_HOUR`
    FOREIGN KEY (`HOUR_id`)
    REFERENCES `WEATHER_HOUR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_WEATHER_DAY1`
    FOREIGN KEY (`DAY_id`)
    REFERENCES `WEATHER_DAY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phonenumber` CHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phonenumber_UNIQUE` (`phonenumber` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `DISPLAY` (
  `USER_id` INT NOT NULL,
  `WEATHER_id` INT NOT NULL,
  `rank_display` INT NOT NULL,
  INDEX `fk_table1_user1_idx` (`USER_id` ASC),
  INDEX `fk_table1_WEATHER_DAY2_idx` (`WEATHER_id` ASC),
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_WEATHER_DAY2`
    FOREIGN KEY (`WEATHER_id`)
    REFERENCES `WEATHER_DAY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
